name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'content/**'
      - '.github/workflows/build-deploy.yml'

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the entire repo (so 'make clean' works)
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Install Pandoc, make, jq
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc make jq

      # 3. Force‐clean then rebuild index.html
      - name: Clean & build site
        run: |
          echo "→ Cleaning old output"
          make clean
          echo "→ Running make (force rebuild)"
          make
          echo "→ Files after build:"
          ls -1 .

      # 4. Prepare a 'build' folder with the exact files to publish
      - name: Prepare artifact folder
        run: |
          rm -rf build
          mkdir -p build
          cp index.html build/
          cp -R src build/
          rsync -av --exclude='*.md' --exclude='*.html' content/ build/

      # 5. Upload *only* the contents of 'build/' as the Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/*

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
