name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "content/**"
      - ".github/workflows/build-deploy.yml"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the entire repo (so 'make clean' works)
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Install Pandoc, make, jq
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc make jq

      # 3. Force-clean then run make (output lands in build/index.html)
      - name: Clean & build site
        run: |
          echo "→ Cleaning old output"
          make clean
          echo "→ Running make (build to build/index.html)"
          make
          echo "→ Contents of build/:"
          ls -R build

      # 4. Copy CSS/JS and media into build/
      - name: Copy assets into build
        run: |
          cp -R src build/
          rsync -av --exclude='*.md' --exclude='*.html' content/ build/

      # 5. Upload all files under build/ as the Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      # 7. Commit and open a PR with updated build/ folder
      - name: Create Pull Request for build/ updates
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "ci: update build folder"
          branch: "auto/update-build-${{ github.run_number }}"
          title: "chore: update build folder"
          body: "Auto-generated update of the build/ directory"
          path: build/**
