# .github/workflows/build-deploy.yml
name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo
      - name: Checkout main
        uses: actions/checkout@v4

      # Install system dependencies (pandoc, make, jq)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc make jq

      # Build via 'make'
      - name: Build site (pandoc → index.html)
        run: |
          echo "→ Running make…"
          make

      # Upload the generated index.html
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: |
            index.html

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
